[package]
name = "uds-receiver"
version = "0.1.0"
edition = "2024"
authors = ["Ibuki.O <isan.ethen@gmail.com>"]

[[bin]]
name = "uds-receiver"
path = "src/main.rs"

[dependencies]
libc = "0.2.172"
libredox = "0.1.3"
redox_syscall = "0.5"
